### ISSUE TITLE
Problem handling gff aggregated genes

### ISSUE THREAD

**Issue by DrAnomalocaris** [Anomalo/eon#2]
Analyzing 15AL_15DR.01.csv
retrving sequence for  ENSMUSG00000024070 foreground
retrving sequence for  ENSMUSG00000024070 background
retrving sequence for  ENSMUSG00000090264+ENSMUSG00000024483 foreground
retrving sequence for  ENSMUSG00000090264+ENSMUSG00000024483 background
Traceback (most recent call last):
  File "dexMotif.py", line 108, in <module>
    main()
  File "dexMotif.py", line 104, in main
    dexMotif.addMotifs()
  File "/nfs/research2/enright/albert/tools/eon/eon/dex.py", line 31, in addMotifs
    tempFasta ,ids= self.dexSeqToFasta()
  File "/nfs/research2/enright/albert/tools/eon/eon/dex.py", line 175, in dexSeqToFasta
    avoid_end  =end)))
  File "/nfs/research2/enright/albert/tools/eon/eon/gtf.py", line 217, in getGeneCoords
    return GTF.getGeneCoords(gene,avoid_start,avoid_end)
  File "/nfs/research2/enright/albert/tools/eon/eon/gtf.py", line 152, in getGeneCoords
    for exon in self.transcriptNamesFromID(ID):
  File "/nfs/research2/enright/albert/tools/eon/eon/gtf.py", line 199, in transcriptNamesFromID
    return self.gene_IDS[ID]
KeyError: 'ENSMUSG00000090264+ENSMUSG00000024483'

**Comment by DrAnomalocaris** [comment]
fixed.
